### ISSUE TITLE
Bump versions

### ISSUE THREAD

**Issue by Tomas2D** [i-am-bee/bee-stack#60]
The `docker-compose.yml` file refers to outdated API and UI images.

Latest API: 0.0.17
Latest UI: 0.0.11

**Comment by psschwei** [comment]
fwiw, I got an error running against the new api image :

```
bee-api-1  | ts-node not installed, support for working with TS files might not work
bee-api-1  | mikro-orm seeder:run
bee-api-1  | 
bee-api-1  | Seed the database using the seeder class
bee-api-1  | 
bee-api-1  | Options:
bee-api-1  |       --config   Set path to the ORM configuration file                 [string]
bee-api-1  |   -c, --class    Seeder class to run                                    [string]
bee-api-1  |   -v, --version  Show version number                                   [boolean]
bee-api-1  |   -h, --help     Show help                                             [boolean]
bee-api-1  | 
bee-api-1  | Error: Unknown items runs:cleanup,vectorStores:cleanup,vectorStores:fileProcessor,files:extraction:node in RUN_BULLMQ_WORKERS
bee-api-1  |     at getStringArray (file:///app/dist/config.js:16:35)
bee-api-1  |     at file:///app/dist/config.js:106:28
bee-api-1  |     at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
bee-api-1  |     at async ModuleLoader.import (node:internal/modules/esm/loader:475:24)
bee-api-1  |     at async ConfigurationLoader.getConfiguration (/app/node_modules/.pnpm/@mikro-orm+core@6.2.9/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:28:32)
bee-api-1  |     at async CLIHelper.getORM (/app/node_modules/.pnpm/@mikro-orm+cli@6.2.9_sqlite3@5.1.7/node_modules/@mikro-orm/cli/CLIHelper.js:22:25)
bee-api-1  |     at async Object.handler (/app/node_modules/.pnpm/@mikro-orm+cli@6.2.9_sqlite3@5.1.7/node_modules/@mikro-orm/cli/commands/DatabaseSeedCommand.js:21:21)
bee-api-1  | npm notice
bee-api-1  | npm notice New minor version of npm available! 10.7.0 -> 10.9.2
bee-api-1  | npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.2
bee-api-1  | npm notice To update run: npm install -g npm@10.9.2
bee-api-1  | npm notice
bee-api-1  | Error occured
bee-api-1  | ts-node not installed, support for working with TS files might not work
bee-api-1  | mikro-orm seeder:run
bee-api-1  | 
bee-api-1  | Seed the database using the seeder class
bee-api-1  | 
bee-api-1  | Options:
bee-api-1  |       --config   Set path to the ORM configuration file                 [string]
bee-api-1  |   -c, --class    Seeder class to run                                    [string]
bee-api-1  |   -v, --version  Show version number                                   [boolean]
bee-api-1  |   -h, --help     Show help                                             [boolean]
bee-api-1  | 
bee-api-1  | Error: Unknown items runs:cleanup,vectorStores:cleanup,vectorStores:fileProcessor,files:extraction:node in RUN_BULLMQ_WORKERS
bee-api-1  |     at getStringArray (file:///app/dist/config.js:16:35)
bee-api-1  |     at file:///app/dist/config.js:106:28
bee-api-1  |     at ModuleJob.run (node:internal/modules/esm/module_job:262:25)
bee-api-1  |     at async ModuleLoader.import (node:internal/modules/esm/loader:475:24)
bee-api-1  |     at async ConfigurationLoader.getConfiguration (/app/node_modules/.pnpm/@mikro-orm+core@6.2.9/node_modules/@mikro-orm/core/utils/ConfigurationLoader.js:28:32)
bee-api-1  |     at async CLIHelper.getORM (/app/node_modules/.pnpm/@mikro-orm+cli@6.2.9_sqlite3@5.1.7/node_modules/@mikro-orm/cli/CLIHelper.js:22:25)
bee-api-1  |     at async Object.handler (/app/node_modules/.pnpm/@mikro-orm+cli@6.2.9_sqlite3@5.1.7/node_modules/@mikro-orm/cli/commands/DatabaseSeedCommand.js:21:21)
bee-api-1  | Error occured
```

**Comment by Tomas2D** [comment]
Exactly. To bump versions we must make some additional changes; that's why this issue has been assigned to @jezekra1

**Comment by Tomas2D** [comment]
Working. Great job @jezekra1 🚀
